     name: 'My Docker Action'
     description: 'A custom Docker action'
     inputs:
       name:
         description: 'The name to greet'
         required: true
     runs:
       using: 'docker'
       image: 'Dockerfile'
       args:
         - ${{ inputs.name }}
