    name: Use Secrets and Env Variables

    on: [push]

    jobs:
      use_secrets_job:
        runs-on: ubuntu-latest
        environment: env1

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Print secret
          run: echo ${{ secrets.MY_SECRET }} > 1.txt
        - name: Print env secret
          run: echo ${{ env.VAR1 }} > 2.txt

        - name: Print environment variable
          env:
            MY_ENV_VAR: 'Hello, Environment!'
          run: |
            echo $MY_ENV_VAR
            echo $VAR1

        - name: Run tmate
          uses: mxschmitt/action-tmate@v2